### ISSUE TITLE
Validate Data On Load

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/web-mapping-components#20]
Robert:

> I did see a console error when I tried to load a new map style document from mapbox which uses geojson datasets (i.e. when we change the map from one dataset to the another which uses geojson datasets hosted on mapbox (e.g. odhf)) but from debugging I haven't found the reason for it occurring yet, and the layer still displays as expected on the map. 
>  
> I suspect the cause of the issue is that the data isn't fully downloaded before it tries to update the layer styling, but I'll look into it further when time allows. More than likely we will need to expand the code to be bit when using external data sources, which we would likely need to do anyway since we are moving to our own db host. e.g. If maplibre doesn't do this already, our code should check if we have all of the data before we try to update the map layers which use that external data.

**Comment by roikle** [comment]
Mapbox provides numerous built-in map events relating to processing source data. See [mapbox-gl api docs](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-events) for additional information. 

Examples of map data events: data, dataloading, sourcedata, and souredataloading.

According to [map data event documentation](https://docs.mapbox.com/mapbox-gl-js/api/events/#mapdataevent), data events have a property `isSourceLoaded` which could be used in a condition to then continue loading the next source data file. Once all source data has been loaded, you could then add map layers which have sources.

**Comment by roikle** [comment]
Added mapbox sourcedata event to the map module (see commit 36b1cd36afe7becbccdec5604e1cf496fb3bd9fb). Now when making an application a developer can load each data source, and confirm when the source is loaded before using it.
